
version: '3.8'

services:

  postgres:

    image: postgres:latest
    
    container_name: task_manager_db
    
    environment:

      POSTGRES_USER: postgres_user  
      POSTGRES_PASSWORD: postgres_admin
      POSTGRES_DB: task_manager_db

    ports:
      - "5432:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    restart: always

volumes:
  postgres_data:
