services:
  db:
    image: postgres:14
    container_name: unlocker_api_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unlockerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unlocker_api_web
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./src:/app
    working_dir: /app/Ecommerce.WebApi

volumes:
  pgdata:
