version: "3.9"

services:
  db:
    image: postgres:16
    container_name: unlocker_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unlockerdb
    ports:
      - "5432:5432"
    volumes:
      - unlocker_pgdata:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unlocker_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgresConnection: "Host=db;Port=5432;Database=unlockerdb;Username=postgres;Password=postgres"
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  unlocker_pgdata: